CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users (
ID integer primary key,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)"""


INSERT_USER_QUERY = """
INSERT INTO telegram_users VALUES (?,?,?,?,?)
"""


SELECT_ALL_USERS_QUERY = """
SELECT FIRST_NAME FROM telegram_users
"""


CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profiles (
ID integer primary key,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
BIO TEXT,
IS_MARRIED CHAR(50),
MALE CHAR(50),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)"""


INSERT_PROFILE_QUERY = """
INSERT INTO profiles VALUES (?,?,?,?,?,?,?)
"""


SELECT_ALL_PROFILES_QUERY = """
SELECT * FROM profiles p
WHERE p.TELEGRAM_ID NOT IN (
    SELECT ld.OWNER_ID
    FROM like_dislike ld
    WHERE ld.LIKER_ID = ?
    AND ld.STATUS IS NOT NULL 
)
AND p.TELEGRAM_ID != ?
"""


CREATE_LIKE_DISLIKE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS like_dislike (
ID integer primary key,
OWNER_ID INTEGER,
LIKER_ID INTEGER,
STATUS INTEGER,
UNIQUE (OWNER_ID, LIKER_ID)
)"""


INSERT_LIKE_QUERY = """
INSERT INTO like_dislike VALUES (?,?,?,?)
"""


SELECT_ONE_PROFILE_QUERY = """
SELECT * FROM profiles WHERE TELEGRAM_ID = ?
"""


UPDATE_PROFILE_QUERY = """
UPDATE profiles SET NICKNAME = ?, BIO = ?, IS_MARRIED = ?, MALE = ?, PHOTO = ? WHERE TELEGRAM_ID = ?
"""


DELETE_PROFILE_QUERY = """
DELETE  FROM profiles WHERE TELEGRAM_ID = ?
"""


